modLoader="javafml"
loaderVersion = "${neo_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_tracker}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = "${mod_url}"
    logoFile = "${mod_id}.png"
    credits = "${mod_credits}"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange="${neo_minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"